// Copyright 2026 Adefebrian (https://adefebrian.com). Built by Adefebrian. Noncommercial use only, see LICENSE.
// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// Static checks for the island on the notch: the contract the web page builds
// against (window label, page, the three commands), the capability that only
// the island window gets, the window flags, the macOS-only dependencies and the
// tray setting. The geometry math, path validation, setting and capability are
// unit tested in Rust (src/island.rs, src/settings.rs). No network, no cargo.
import { describe, expect, test } from "bun:test";
import { existsSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { tauriDir } from "./lib";

const read = (rel: string) => Bun.file(join(tauriDir, rel)).text();
const json = async <T = any>(rel: string): Promise<T> => JSON.parse(await read(rel)) as T;
/** Shipped code only: the part of a Rust file before its unit tests. */
const shipped = async (rel: string) => (await read(rel)).split("#[cfg(test)]\nmod tests")[0]!;

const COMMANDS = ["island_geometry", "island_set_state", "island_open_main"] as const;
const PERMISSIONS = COMMANDS.map((c) => `allow-${c.replaceAll("_", "-")}`);

describe("island contract", () => {
  test("window label, page and commands match what the web page calls", async () => {
    const island = await read("src/island.rs");
    expect(island).toContain('pub const ISLAND_WINDOW: &str = "island";');
    expect(island).toContain('pub const ISLAND_PATH: &str = "/island";');
    expect(island).toContain('format!("{}{ISLAND_PATH}", window::origin(port))');
    expect(island).toContain(`pub const COMMANDS: [&str; 3] = [${COMMANDS.map((c) => `"${c}"`).join(", ")}];`);
    expect(island).toContain(`pub const PERMISSIONS: [&str; 3] = [${PERMISSIONS.map((p) => `"${p}"`).join(", ")}];`);
    for (const c of COMMANDS) expect(island).toContain(`pub fn ${c}(`);
    // Geometry keys in camelCase, states in lowercase, as the contract spells them.
    expect(island).toContain('#[serde(rename_all = "camelCase")]\npub struct Geometry {');
    for (const field of ["has_notch: bool", "notch_width: f64", "notch_height: f64", "menu_bar_height: f64", "scale: f64"]) {
      expect(island).toContain(`pub ${field},`);
    }
    expect(island).toContain('#[serde(rename_all = "lowercase")]\npub enum IslandState {\n    Collapsed,\n    Peek,\n    Expanded,\n}');
    expect(island).toMatch(/pub fn island_set_state\(\s*app: AppHandle,\s*window: WebviewWindow,\s*state: IslandState,\s*width: f64,\s*height: f64,\s*\)/);
    expect(island).toMatch(/pub fn island_open_main\(app: AppHandle, window: WebviewWindow, path: String\)/);
  });

  test("the shell registers the three commands and gates them in the app manifest", async () => {
    const main = await read("src/main.rs");
    for (const c of COMMANDS) expect(main).toContain(`island::${c}`);
    const build = await read("build.rs");
    for (const c of ["pick_folder", ...COMMANDS]) expect(build).toContain(`"${c}",`);
    for (const [c, p] of COMMANDS.map((c, i) => [c, PERMISSIONS[i]!] as const)) {
      const toml = await read(`permissions/autogenerated/${c}.toml`);
      expect(toml).toContain(`identifier = "${p}"`);
      expect(toml).toContain(`commands.allow = ["${c}"]`);
    }
  });
});

describe("island capability", () => {
  test("only the island window gets the commands, for the exact engine origin, never local content", async () => {
    const island = await shipped("src/island.rs");
    expect(island).toContain('pub const CAPABILITY: &str = "island-origin";');
    expect(island).toContain(
      "CapabilityBuilder::new(CAPABILITY).remote(window::origin(port)).local(false).window(ISLAND_WINDOW)",
    );
    expect(island).toContain("app.add_capability(capability(port))");
    // Second check inside every command: the caller must be the island window.
    expect(island.match(/only_island\(&window\)\?;/g)?.length).toBe(COMMANDS.length);
  });

  test("the main window keeps its own grant and no capability file names the island", async () => {
    const win = await shipped("src/window.rs");
    const grant = /pub fn main_capability\(port: u16\) -> CapabilityBuilder \{([^}]*)\}/.exec(win)?.[1] ?? "";
    expect(grant).toContain('.window(MAIN_WINDOW).permission("allow-pick-folder")');
    expect(grant).not.toContain("island");
    expect(win).toContain("app.add_capability(main_capability(port))?;");
    expect(readdirSync(join(tauriDir, "capabilities"))).toEqual(["main.json"]);
    const main = await json("capabilities/main.json");
    expect(main.windows).toEqual(["main"]);
    expect(JSON.stringify(main)).not.toContain("island");
    expect((await json("tauri.conf.json")).app.security.capabilities).toEqual(["main"]);
  });
});

describe("island window", () => {
  test("transparent through macOSPrivateApi, which the Cargo feature matches", async () => {
    const conf = await json("tauri.conf.json");
    expect(conf.app.macOSPrivateApi).toBe(true);
    expect(conf.app.windows).toEqual([]);
    const cargo = await read("Cargo.toml");
    expect(cargo).toMatch(/^tauri = \{ version = "2\.12", features = \["tray-icon", "macos-private-api"\] \}$/m);
    // The dmg is the only macOS channel: the private API rules out the Mac App Store.
    expect(conf.bundle.targets).toEqual(["app", "dmg"]);
  });

  test("borderless, shadowless, fixed, on every Space, above the menu bar, never activating", async () => {
    const island = await shipped("src/island.rs");
    for (const flag of [
      ".decorations(false)",
      ".transparent(true)",
      ".shadow(false)",
      ".resizable(false)",
      ".skip_taskbar(true)",
      ".visible_on_all_workspaces(true)",
      ".visible(false)",
      ".focused(false)",
      ".accept_first_mouse(true)",
      ".on_navigation(move |url| is_island_url(url, port))",
      "NewWindowResponse::Deny",
      "NSWindowCollectionBehavior::CanJoinAllSpaces",
      "NSWindowCollectionBehavior::FullScreenAuxiliary",
      "NSWindowCollectionBehavior::Stationary",
      "ns.setLevel(NSMainMenuWindowLevel + LEVELS_ABOVE_MENU_BAR);",
      "ns.setHasShadow(false);",
      "ns.orderFrontRegardless();",
      "ns.setFrame_display(",
    ]) {
      expect(island).toContain(flag);
    }
    // Hover works while it is not key: WebKit's key-window-only tracking areas get always active copies.
    expect(island).toContain("track_always(&content, 0);");
    expect(island).toContain("pub const IN_KEY_WINDOW: usize = 0x20;");
    expect(island).toContain("pub const ALWAYS: usize = 0x80;");
    // Never made key or activated when it appears.
    expect(island).not.toContain("makeKeyAndOrderFront");
    expect(island).not.toContain("activateIgnoringOtherApps");
    expect(island).not.toContain(".set_focus()");
  });

  test("geometry comes from the notch through AppKit and follows display changes", async () => {
    const island = await shipped("src/island.rs");
    for (const call of ["safeAreaInsets()", "auxiliaryTopLeftArea()", "auxiliaryTopRightArea()", "backingScaleFactor()"]) {
      expect(island).toContain(call);
    }
    expect(island).toContain("NSApplicationDidChangeScreenParametersNotification");
    expect(island).toContain("NSOperationQueue::mainQueue()");
    expect(island).toContain('#[cfg(target_os = "macos")]\nmod native {');
  });

  test("the AppKit crates are macOS only and already in the lockfile", async () => {
    const cargo = await read("Cargo.toml");
    const mac = cargo.slice(cargo.indexOf(`[target.'cfg(target_os = "macos")'.dependencies]`));
    const section = mac.slice(0, mac.indexOf("\n[", 1));
    const lock = await read("Cargo.lock");
    for (const crate of ["objc2", "block2", "objc2-foundation", "objc2-app-kit"]) {
      expect(section).toMatch(new RegExp(`^${crate} = `, "m"));
      expect(lock).toContain(`name = "${crate}"`);
    }
    // No default features on the framework crates (they would compile all of AppKit and Foundation).
    expect(section).toContain('objc2-foundation = { version = "0.3", default-features = false');
    expect(section).toContain('objc2-app-kit = { version = "0.3", default-features = false');
  });
});

describe("island lifecycle", () => {
  test("opens after the engine is ready, closes on kill switch and quit, Cmd+W cannot close it", async () => {
    const main = await read("src/main.rs");
    const supervise = main.slice(main.indexOf("fn supervise("), main.indexOf("fn exit_text("));
    expect(supervise.indexOf("island::engine_ready(&app, ready.port)")).toBeGreaterThan(
      supervise.indexOf("window::open_main(&app, ready.port)"),
    );
    const kill = main.slice(main.indexOf("fn trigger_killswitch("), main.indexOf("fn settings_item("));
    expect(kill).toContain("island::stop_for_session(app);");
    const menu = main.slice(main.indexOf("fn on_menu("), main.indexOf("fn toggle_island("));
    expect(menu.indexOf("island::close(app);")).toBeLessThan(menu.indexOf("app.exit(0);"));
    expect(main).toMatch(/RunEvent::ExitRequested \{ \.\. \} => \{[^}]*\}\s*island::close\(app\);/);
    expect(main).toContain("if label == island::ISLAND_WINDOW =>");
  });

  test("the tray check item toggles it live and saves only the island key", async () => {
    const island = await read("src/island.rs");
    expect(island).toContain('CheckMenuItem::with_id(app, MENU_ISLAND, "Show island", true, false, None::<&str>)');
    expect(island).toContain('if !cfg!(target_os = "macos") {\n        return Ok(None);');
    const main = await read("src/main.rs");
    expect(main).toContain("island::MENU_ISLAND => toggle_island(app),");
    expect(main).toContain("settings::set_island(path, on)");
    expect(main).toContain("island::apply_setting(app, loaded.island);");
    const settings = await read("src/settings.rs");
    expect(settings).toContain("island: Option<bool>,");
    expect(settings).toContain("let island = raw.island.unwrap_or(true);");
    expect(settings).toContain("pub fn set_island(path: &Path, on: bool) -> Result<(), String>");
  });

  test("new source files carry the license header", async () => {
    for (const rel of ["src/island.rs", "../scripts/island.test.ts"]) {
      const lines = (await read(rel)).split("\n");
      expect(lines[0]).toContain("Copyright 2026 Adefebrian (https://adefebrian.com). Built by Adefebrian.");
      expect(lines[1]).toContain("SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0");
    }
    expect(existsSync(join(tauriDir, "src", "island.rs"))).toBe(true);
  });
});
