// Copyright 2026 Adefebrian (https://adefebrian.com). Built by Adefebrian. Noncommercial use only, see LICENSE.
// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// BYOK provider presets. A preset only pre-fills the form: the user can edit
// the base URL and type any model id. Everything that speaks OpenAI Chat
// Completions or Anthropic Messages works through the two chat adapters, so
// "custom" covers any vendor not listed here (local proxies included).
import type { ProviderCap, ProviderProtocol } from "./enums";

export interface ProviderPreset {
  id: string;
  label: string;
  protocol: ProviderProtocol;
  baseUrl: string;
  /** how the key is sent; the adapter owns the exact header */
  auth: "bearer" | "x-api-key" | "x-goog-api-key" | "fal-key" | "none";
  keyRequired: boolean;
  caps: ProviderCap[];
  /** suggestions only; "Test connection" fetches the real list when the vendor supports GET /models */
  suggestedModels: string[];
  /** vendor usage field names for cached prompt tokens, normalized by the adapter */
  cacheUsage: "openai" | "anthropic" | "deepseek" | "gemini" | "none";
  /** loopback base URLs are allowed only in local mode */
  local?: boolean;
  docsUrl: string;
}

const CHAT: ProviderCap[] = ["chat", "tools"];

export const PROVIDER_PRESETS: ProviderPreset[] = [
  {
    id: "openai",
    label: "OpenAI",
    protocol: "openai_chat",
    baseUrl: "https://api.openai.com/v1",
    auth: "bearer",
    keyRequired: true,
    caps: ["chat", "tools", "vision"],
    suggestedModels: ["gpt-4o-mini", "gpt-4.1-mini", "gpt-4.1", "gpt-5-mini", "gpt-5"],
    cacheUsage: "openai",
    docsUrl: "https://platform.openai.com/docs/api-reference/chat",
  },
  {
    id: "openai-media",
    label: "OpenAI images and video",
    protocol: "openai_images",
    baseUrl: "https://api.openai.com/v1",
    auth: "bearer",
    keyRequired: true,
    caps: ["image", "video"],
    suggestedModels: ["gpt-image-2", "gpt-image-1.5", "gpt-image-1-mini", "sora-2"],
    cacheUsage: "none",
    docsUrl: "https://platform.openai.com/docs/api-reference/images",
  },
  {
    id: "anthropic",
    label: "Anthropic Claude",
    protocol: "anthropic_messages",
    baseUrl: "https://api.anthropic.com",
    auth: "x-api-key",
    keyRequired: true,
    caps: ["chat", "tools", "vision"],
    suggestedModels: ["claude-sonnet-5-5", "claude-haiku-4-5-20251001", "claude-opus-5-5"],
    cacheUsage: "anthropic",
    docsUrl: "https://docs.anthropic.com/en/api/messages",
  },
  {
    id: "deepseek",
    label: "DeepSeek",
    protocol: "openai_chat",
    baseUrl: "https://api.deepseek.com/v1",
    auth: "bearer",
    keyRequired: true,
    caps: CHAT,
    suggestedModels: ["deepseek-chat", "deepseek-reasoner"],
    cacheUsage: "deepseek",
    docsUrl: "https://api-docs.deepseek.com/",
  },
  {
    id: "mimo",
    label: "Xiaomi MiMo",
    protocol: "openai_chat",
    baseUrl: "https://api.xiaomimimo.com/v1",
    auth: "bearer",
    keyRequired: true,
    caps: CHAT,
    suggestedModels: ["mimo-v2-flash"],
    cacheUsage: "openai",
    docsUrl: "https://platform.xiaomimimo.com/",
  },
  {
    id: "agentrouter",
    label: "AgentRouter",
    protocol: "openai_chat",
    baseUrl: "https://agentrouter.org/v1",
    auth: "bearer",
    keyRequired: true,
    caps: CHAT,
    suggestedModels: [],
    cacheUsage: "openai",
    docsUrl: "https://agentrouter.org/",
  },
  {
    id: "openrouter",
    label: "OpenRouter",
    protocol: "openai_chat",
    baseUrl: "https://openrouter.ai/api/v1",
    auth: "bearer",
    keyRequired: true,
    caps: ["chat", "tools", "vision"],
    suggestedModels: ["openai/gpt-4o-mini", "anthropic/claude-sonnet-5.5", "deepseek/deepseek-chat"],
    cacheUsage: "openai",
    docsUrl: "https://openrouter.ai/docs",
  },
  {
    id: "gemini",
    label: "Google Gemini",
    protocol: "openai_chat",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta/openai",
    auth: "bearer",
    keyRequired: true,
    caps: ["chat", "tools", "vision"],
    suggestedModels: ["gemini-2.5-flash", "gemini-2.5-pro"],
    cacheUsage: "openai",
    docsUrl: "https://ai.google.dev/gemini-api/docs/openai",
  },
  {
    id: "gemini-media",
    label: "Google Gemini images and Veo",
    protocol: "gemini_media",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta",
    auth: "x-goog-api-key",
    keyRequired: true,
    caps: ["image", "video"],
    suggestedModels: ["gemini-3.1-flash-image", "veo-3.1-generate-preview"],
    cacheUsage: "none",
    docsUrl: "https://ai.google.dev/gemini-api/docs/veo",
  },
  {
    id: "groq",
    label: "Groq",
    protocol: "openai_chat",
    baseUrl: "https://api.groq.com/openai/v1",
    auth: "bearer",
    keyRequired: true,
    caps: CHAT,
    suggestedModels: [],
    cacheUsage: "openai",
    docsUrl: "https://console.groq.com/docs/openai",
  },
  {
    id: "mistral",
    label: "Mistral",
    protocol: "openai_chat",
    baseUrl: "https://api.mistral.ai/v1",
    auth: "bearer",
    keyRequired: true,
    caps: CHAT,
    suggestedModels: ["mistral-small-latest", "mistral-large-latest"],
    cacheUsage: "openai",
    docsUrl: "https://docs.mistral.ai/api",
  },
  {
    id: "xai",
    label: "xAI Grok",
    protocol: "openai_chat",
    baseUrl: "https://api.x.ai/v1",
    auth: "bearer",
    keyRequired: true,
    caps: CHAT,
    suggestedModels: [],
    cacheUsage: "openai",
    docsUrl: "https://docs.x.ai/",
  },
  {
    id: "moonshot",
    label: "Moonshot Kimi",
    protocol: "openai_chat",
    baseUrl: "https://api.moonshot.ai/v1",
    auth: "bearer",
    keyRequired: true,
    caps: CHAT,
    suggestedModels: [],
    cacheUsage: "openai",
    docsUrl: "https://platform.moonshot.ai/docs",
  },
  {
    id: "zhipu",
    label: "Z.ai GLM",
    protocol: "openai_chat",
    baseUrl: "https://api.z.ai/api/paas/v4",
    auth: "bearer",
    keyRequired: true,
    caps: CHAT,
    suggestedModels: [],
    cacheUsage: "openai",
    docsUrl: "https://docs.z.ai/",
  },
  {
    id: "qwen",
    label: "Alibaba Qwen",
    protocol: "openai_chat",
    baseUrl: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
    auth: "bearer",
    keyRequired: true,
    caps: CHAT,
    suggestedModels: [],
    cacheUsage: "openai",
    docsUrl: "https://www.alibabacloud.com/help/en/model-studio/",
  },
  {
    id: "minimax",
    label: "MiniMax",
    protocol: "openai_chat",
    baseUrl: "https://api.minimax.io/v1",
    auth: "bearer",
    keyRequired: true,
    caps: CHAT,
    suggestedModels: [],
    cacheUsage: "openai",
    docsUrl: "https://www.minimax.io/platform",
  },
  {
    id: "together",
    label: "Together AI",
    protocol: "openai_chat",
    baseUrl: "https://api.together.ai/v1",
    auth: "bearer",
    keyRequired: true,
    caps: CHAT,
    suggestedModels: [],
    cacheUsage: "openai",
    docsUrl: "https://docs.together.ai/",
  },
  {
    id: "fireworks",
    label: "Fireworks AI",
    protocol: "openai_chat",
    baseUrl: "https://api.fireworks.ai/inference/v1",
    auth: "bearer",
    keyRequired: true,
    caps: CHAT,
    suggestedModels: [],
    cacheUsage: "openai",
    docsUrl: "https://docs.fireworks.ai/",
  },
  {
    id: "ollama",
    label: "Ollama (local)",
    protocol: "openai_chat",
    baseUrl: "http://localhost:11434/v1",
    auth: "none",
    keyRequired: false,
    caps: CHAT,
    suggestedModels: [],
    cacheUsage: "none",
    local: true,
    docsUrl: "https://docs.ollama.com/api/openai-compatibility",
  },
  {
    id: "lmstudio",
    label: "LM Studio (local)",
    protocol: "openai_chat",
    baseUrl: "http://localhost:1234/v1",
    auth: "none",
    keyRequired: false,
    caps: CHAT,
    suggestedModels: [],
    cacheUsage: "none",
    local: true,
    docsUrl: "https://lmstudio.ai/docs/developer/openai-compat",
  },
  {
    id: "custom-openai",
    label: "Custom, OpenAI compatible",
    protocol: "openai_chat",
    baseUrl: "",
    auth: "bearer",
    keyRequired: false,
    caps: CHAT,
    suggestedModels: [],
    cacheUsage: "openai",
    docsUrl: "https://platform.openai.com/docs/api-reference/chat",
  },
  {
    id: "custom-anthropic",
    label: "Custom, Anthropic compatible",
    protocol: "anthropic_messages",
    baseUrl: "",
    auth: "x-api-key",
    keyRequired: false,
    caps: CHAT,
    suggestedModels: [],
    cacheUsage: "anthropic",
    docsUrl: "https://docs.anthropic.com/en/api/messages",
  },
  {
    id: "fal",
    label: "fal.ai",
    protocol: "fal_queue",
    baseUrl: "https://queue.fal.run",
    auth: "fal-key",
    keyRequired: true,
    caps: ["image", "video"],
    suggestedModels: [],
    cacheUsage: "none",
    docsUrl: "https://docs.fal.ai/model-apis/model-endpoints/queue",
  },
  {
    id: "replicate",
    label: "Replicate",
    protocol: "replicate",
    baseUrl: "https://api.replicate.com/v1",
    auth: "bearer",
    keyRequired: true,
    caps: ["image", "video"],
    suggestedModels: [],
    cacheUsage: "none",
    docsUrl: "https://replicate.com/docs/reference/http",
  },
  {
    id: "jev",
    label: "JEV judge",
    protocol: "jev",
    baseUrl: "https://api.typesafe.ai/v1",
    auth: "bearer",
    keyRequired: true,
    caps: ["judge"],
    // key only: the official endpoint is fixed and JEV picks its own version, so there is no model to set
    suggestedModels: [],
    cacheUsage: "none",
    docsUrl: "https://typesafe.ai/",
  },
];

export function findPreset(id: string): ProviderPreset | undefined {
  return PROVIDER_PRESETS.find((p) => p.id === id);
}
